name: CmakeTest
on:
  push:
    branches: main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: update system
    # Runs a set of commands using the runners shell
      run: |
         sudo apt-get update
         sudo apt-get install -y build-essential
         sudo apt-get install -y cmake make
    
    - run: mkdir build && cd build
    - run: cmake
    
    - name: Archive code coverage results
      uses: actions/checkout@v3
      with:
         name: build
         path: build/main
